---
title: Incoming
---

## Where to start

On the page of the [International Relations Office](https://ib.wiso.fau.de/income/) you will find a lot of useful information:

-   [FAQ](https://ib.wiso.fau.de/income/faq/) for foreign Students

-   [Planning](https://ib.wiso.fau.de/income/planning/) your stay and [first steps](https://ib.wiso.fau.de/income/to-do-first/)

-   Special events/programmes for orientation at FAU, like the [central welcome weeks](https://www.fau.eu/education/international/from-abroad/welcome-programme-for-international-students/orientation-courses-for-international-students/) or the [Buddy programme](https://www.fau.eu/education/international/from-abroad/welcome-programme-for-international-students/buddy-programme/)

## Lectures

The Chair and the Junior Professorship of Communication Studies offers various courses in English in both the Bachelor's and Master's programmes:

| Programm | Title | Type | Term |
|-----------------|-----------------------|-----------------|-----------------|
| Bachelor | [Digital Technologies & Society](https://www.kommunikationswissenschaft.rw.fau.de/lehre/bachelor/digital-technologies-and-society/) | Lecture | Summer |
| Bachelor | [Hot Topics in International Communication Research](https://www.kommunikationswissenschaft.rw.fau.de/lehre/bachelor/hot-topics/) | Seminar | Summer & Winter |
| Master | [Media Psychology and Effects](https://www.kommunikationswissenschaft.rw.fau.de/lehre/master/media-psychology-and-effects/) | Seminar | Winter |

## Contact

::: callout-important
Please send all emails with inquiries regarding Learning Agreements or other ERASMUS-related matters to: [wiso-erasmus-kowi\@fau.de](mailto:wiso-erasmus-kowi@fau.de)
:::

[**Julius Klingelhöfer (he/him)**](mailto:wiso-erasmus-kowi@fau.de)

Contact person for organizational and content-related ERASMUS matters & Learning Agreements.