---
title: "Overview"
format: html
---

## News and important dates

<!-- FIXED Nennung des Termins für die Infoveranstaltung im Department (normalerweise vor Bewerbungstermin). Ggf. Link zu International Day der Fakultät. Optional Hinweis auf RIA Infoveranstaltungen: https://www.fau.de/education/international/wege-ins-ausland/erste-schritte-zum-auslandsaufenthalt/informationsveranstaltungen/   (wird in Kürze aktualisiert) -->

For the academic year 2024/2025, Communication Science students have the opportunity to study at various partner universities of the [Chair of Communication Science](https://www.kowi.rw.fau.de/) in other European countries as part of the ERASMUS program. Please take note of the following important dates:

-   05.11.2024 - [Presentation](slides/international_day.html) as part of the [International Day](https://www.wiso-international-day.fau.de/)
-   15.11.2024 - Activation of the online application
-   05.12.2024 - Application deadline

## Information for Outgoing students

click [here](outgoing.html) for:

-   a chart of all partner universities for ERASMUS+ of the chair, providing information on available places, duration of stay and languages of teaching
-   general and chair-specific participation requirements, before and during the stay abroad
-   general information on the application process and documents
-   useful information and offers to prepare yourself for your stay abroad

### More helpful links

🔗 [Study abroad in Erasmus programme and partner countries](https://www.fau.eu/education/international/going-abroad/studying-abroad/the-erasmus-programme/)

🔗 [General information about studying abroad](https://ib.wiso.fau.de/en/outgo/)

🔗 [Overview of the ERASMUS programme](https://www.fau.eu/fau/welcome-to-fau/internationalisation/erasmus/)

## Information for Incoming students

click [here](incoming.html) for:

-   helpful resources for incoming international students at a university.
-   English-language courses offered by the Chair and Junior Professorship of Communication Studies.

### More helpful links

🔗 [WiSo International Realtions Office](https://ib.wiso.fau.de/income/)

🔗 [Courses offered by the Ziwis (Soft Skills)](https://www.ziwis.fau.eu/home/courses/key-qualifications/)

🔗 [German as a Foreign Language](https://sz.fau.eu/department-german/)

🔗 [Exchange programme students at FAU](https://www.fau.eu/education/international/from-abroad/semester-abroad-at-fau/)

## Contact

::: callout-important
Please send all emails with inquiries regarding Learning Agreements or other ERASMUS-related matters to: 
[wiso-erasmus-kowi\@fau.de](mailto:wiso-erasmus-kowi@fau.de)
:::

**Julius Klingelhöfer (he/him)**

Contact person for organizational and content-related ERASMUS matters & Learning Agreements.